#http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    username: xxxxxxxxx
    password: xxxxxxxxx
    url: jdbc:sqlserver://localhost:1433

  jpa:
    hibernate:
      ddl-auto: update